
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/海盾新联?useUnicode = true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#    username: root
#    password: 1234
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.56:1521:orcl
    username: EID
    password: 123456
mybatis:
  type-aliases-package: com.hd.biz.pojo
  mapper-locations: classpath*:com/hd/biz/mapper/*.xml